runtime: nodejs18
env: standard

service: default

handlers:
  - url: /(.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot))$
    static_files: dist/\1
    upload: dist/.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$
    secure: always

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

env_variables:
  API_URL: "https://api-dot-qualicall-2.uc.r.appspot.com"
  VITE_API_URL: "https://api-dot-qualicall-2.uc.r.appspot.com"
  PROD: "true"
